/*
 * Copyright (c) 2020 · Marton Lederer
 * This file was created / generated by Marton Lederer
 * See the LICENSE on the github repo
 * https://github.com/MartonDev
 * https://marton.lederer.hu
 */

import { Options, Transport, LogLevel, Color } from '../../types.ts'

/*
*
* Console transport
*
* This will log all desired messages to your console
*
* @param level  The levels to log with this transport
* @param options  Custom options for this transport. Same as the global options by default
* @param color
*
* */
export class ConsoleTransport implements Transport {

  level: Array<LogLevel>
  options: Options | undefined

  /*
  *
  * Transport
  *
  * @param level  Only log levels that are included here, logs all by default
  * @param options  Custom options, not required
  *
  * */
  constructor (level: Array<LogLevel>, options?: Options) {

    this.level = level
    this.options = options

  }

  log (level: LogLevel, message: string, options: Options): void {

    if(typeof this.options === 'undefined')
      this.options = options

    for(const lvl in this.level)
      if(this.level[lvl] === level)
        console.log(message)

  }

}