/*
 * Copyright (c) 2020 · Marton Lederer
 * This file was created / generated by Marton Lederer
 * See the LICENSE on the github repo
 * https://github.com/MartonDev
 * https://marton.lederer.hu
 */

import { Transport } from '../../types.ts'

export class ConsoleTransport implements Transport {

  constructor () {



  }

  log (level: number, message: string) {



  }

}