/*
 * Copyright (c) 2020 · Marton Lederer
 * This file was created / generated by Marton Lederer
 * See the LICENSE on the github repo
 * https://github.com/MartonDev
 * https://marton.lederer.hu
 */

/*
*
* Houston options object
*
* */
export interface Options {

  [key: string]: number | string | boolean

}

/*
*
* Houston transport interface to implement
*
* */
export interface Transport {

  /*
  *
  * Logging the message
  *
  * @param level  The level of the log, 0 by default
  * @param message  The log message
  *
  * */
  log(level: number, message: string): void

}